services:
  app:
    build: .
    image: heisenyu/hanime-server:latest
    container_name: hanime-server
    restart: unless-stopped
    environment:
      - USE_PROXY=${USE_PROXY:-false}
      - PROXY_URL=${PROXY_URL:-}
      - PYTHONOPTIMIZE=2
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./data/downloads:/app/backend/downloads
      - ./data/db:/app/backend/db
    ports:
      - "7788:7788"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'