services:
  hanime-server:
    image: ghcr.io/patchourinya/hanime-server:latest
    container_name: hanime-server
    ports:
      - "7788:7788"
    volumes:
      - /volume1/docker/hanime/data:/app/backend/data
      - /volume1/docker/hanime/downloads:/app/backend/downloads
    environment:
      - TZ=Asia/Shanghai
      - USE_PROXY=false
      - PROXY_URL=
    restart: unless-stopped